### ISSUE TITLE
goodork.ru Liliana of the Veil

### ISSUE THREAD

**Issue by refaim** [refaim/wots#35]
```
Process <class 'card.sources.GoodOrk'>:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "app/wizard.py", line 387, in mpEntryPoint
    original(*args, **kwargs)
  File "app/wizard.py", line 397, in queryCardSource
    for cardInfo in cardSource.query(queryString):
  File "/Users/hrt/Pet/wots/app/card/sources.py", line 146, in query
    for cardInfo in self._parseResponse(queryText, requestUrl, response):
  File "/Users/hrt/Pet/wots/app/card/sources.py", line 969, in _parseResponse
    cardName = self._parseDoubleName(nameString.strip())
  File "/Users/hrt/Pet/wots/app/card/sources.py", line 948, in _parseDoubleName
    rusName, engName = re.match(r'^([^(]+?)\s?(?:\(([^)]+)\))?$', nameString).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by refaim** [comment]
Fixed.
