### ISSUE TITLE
Fixer lil crash

### ISSUE THREAD

**Issue by refaim** [refaim/wots#37]
Query: `lil`
Error:
```
Traceback (most recent call last):
  File "C:/Users/Roma/Dropbox/Work/dev/wots/app/wizard.py", line 276, in onTimerTick
    self.searchResultsModel.fetchMore(None)
  File "C:/Users/Roma/Dropbox/Work/dev/wots/app/wizard.py", line 540, in fetchMore
    cardInfo = self.cardsFixer.fixCardInfo(rawCardInfo)
  File "C:\Users\Roma\Dropbox\Work\dev\wots\app\card\fixer.py", line 42, in fixCardInfo
    cardInfo['name']['caption'] = CardUtils.get_primary_name(cardInfo['name']['caption'])
TypeError: string indices must be integers
```

**Comment by refaim** [comment]
Fixed.
